### ISSUE TITLE
Bug for CommitAt 

### ISSUE THREAD

**Issue by MaxBear** [scottdware/go-junos#37]
`if len(message) > 0 {
		command = fmt.Sprintf(rpcCommitAtLog, time)
	}`

Should not it be :
`
if len(message) > 0 {
		command = fmt.Sprintf(rpcCommitAtLog, message)
	}
`

**Comment by scottdware** [comment]
Yup, you are correct! Thanks for catching that! I’ll have it fixed in the morning!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scottdware** [comment]
Should be all set!

**Comment by MaxBear** [comment]
Thanks for fixing this. I have some question about why using an array for message, since you are only taking the first array element as commit message, why not just use a string ? 

`
func (j *Junos) CommitAt(time string, message ...string) error {
	var errs commitResults
	command := fmt.Sprintf(rpcCommitAt, time)

	if len(message) > 0 {
		command = fmt.Sprintf(rpcCommitAtLog, time, message[0])
	}
`

**Comment by scottdware** [comment]
So, this is more so a functionality of Golang and trying to use "optional" parameters in functions. I could just have a static param, and check to see if it's set like:

```Go
CommitAt(time string, message string)

...

if len(message) > 0 { do stuff }
```

But I wanted to make the function easier on the user so that if they forgot to put a message by some chance, it wouldn't error out at them. If the last parameter is a `...string` then that means you could have many optional parameters, but they would all be `message[0], message[1], ...` etc.

**Comment by MaxBear** [comment]
... i think i understand .... message[0] for commit message and other parameters for other purposes, is this right ?

**Comment by scottdware** [comment]
Yup, you got it.
